CREATE TABLE IF NOT EXISTS `product_unit` (
  `unitId` INT NOT NULL AUTO_INCREMENT,
  `unitName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unitId`),
  UNIQUE INDEX `idnew_table_UNIQUE` (`unitId` ASC) VISIBLE
) ENGINE=InnoDB;